import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./globals.css";
import NextTopLoader from 'nextjs-toploader';
import { DarkModeProvider } from "./DarkModeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LinkTweak",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DarkModeProvider>
          <Navbar />
          <div className="duration-300 dark:bg-[#b4b7bf] bg-slate-900 h-[87vh] overflow-x-auto">
            <NextTopLoader /> {children}
          </div>
          <Footer />
        </DarkModeProvider>
      </body>
    </html>
  );
}
















